spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: alirezatestmail@gmail.com
    password: ENC(fh/kqbepiorHngsmQFZE6zKlq4BWKxScKhS+IAljMYRc5Fx2Wt92Z+gLinhbBlQa)
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true