application:
  info:
    name: 'Alireza Alijani Auth Service'
    host: https://localhost:8443
    contact-email: contact@alirezaalijani.ir
  security:
    encryption:
      token:
        secret-key: 'tokenKey'
        salt: '5c0744940b5c369b'
    login:
      theme: default
      validator:
        validate-url: https://localhost:8443/verification/{path}/{token}
      fall:
        max-attempt: 5
        expire-after:
          duration: 1
          unit: DAYS

google:
  recaptcha:
    enable: false
    key:
      site: 6Lf6I_gbAAAAAGd4LniL4OFKq15fz1JjYYTyDb-D # your google key-site
      secret: 6Lf6I_gbAAAAABFPyh08YdWjYOqcNpbsExskU-bY # your google key-secret

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000