spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth_server_db?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: ENC(qjq10h70xEsIDGBYOOVJv8Fo2SuE/SYdt7HPwVT4Sa/51C75vww1I5Gusfh7HrC/) # postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always