server:
  port: 9000

logging:
  file:
    path: ./AuthServiceApplication
    name: AuthServiceApplication/logs/Auth-Service-Application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      clean-history-on-start: true

spring:
  main:
    banner-mode: console
  profiles:
    active: postgres,mail,app,ssl
  thymeleaf:
    cache: false
  mvc:
    log-resolved-exception: off


# all properties can be encrypted by jasypt
#  download jasypt 1.9.3 dist.zip from
#  .bin/encrypt.sh input=<propertyValue> password=<encryptionPassword> algorithm=PBEWITHHMACSHA512ANDAES_256 ivGeneratorClassName=org.jasypt.iv.RandomIvGenerator
jasypt:
  encryptor:
    password: myPassword
    pool-size: 1