version: '3.9'

services:
  auth-service:
    image: ${GROUP_ID}/spring-security-authorization-service:${SERVICE_VERSION:-latest}
    ports:
      - 9000:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "./AuthServiceApplication:/app/AuthServiceApplication/"
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m
      # jasypt config
      JASYPT_ENCRYPTOR_PASSWORD: ${ENCRYPTOR_PASSWORD}
      # postgres config
      POSTGRES_HOST: 172.17.0.1
      POSTGRES_DB: oauth_server_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # mail config
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_HOST_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      # ssl config
      SERVER_SSL_KEY-STORE: ${SERVER_SSL_KEY_STORE}
      SERVER_SSL_KEY-STORE-PASSWORD: ${SERVER_SSL_KEY_STORE_PASSWORD}
      SERVER_SSL_KEY-STORE-TYPE: ${SERVER_SSL_KEY_STORE_TYPE}
      SERVER_SSL_KEY-ALIAS: ${SERVER_SSL_KEY_STORE_ALIAS}
      SERVER_SSL_KEY-PASSWORD: ${SERVER_SSL_KEY_STORE_PASSWORD}
      SERVER_SSL_ENABLED: ${SERVER_SSL_ENABLED}
      SERVER_PORT: ${SERVER_PORT}
      # app config
      SPRING_PROFILES_ACTIVE: ${APPLICATION_PROFILES}
      APPLICATION_INFO_NAME: ${APPLICATION_INFO_NAME}
      APPLICATION_INFO_HOST: ${APPLICATION_INFO_HOST}
      APPLICATION_INFO_CONTACT-EMAIL: ${APPLICATION_INFO_CONTACT-EMAIL}
      # encryption configs
      APPLICATION_SECURITY_ENCRYPTION_TOKEN_SECRET-KEY: ${APPLICATION_SECURITY_ENCRYPTION_TOKEN_SECRET_KEY}
      APPLICATION_SECURITY_ENCRYPTION_TOKEN_SALT: ${APPLICATION_SECURITY_ENCRYPTION_TOKEN_SALT}
      # application security paths
      APPLICATION_SECURITY_LOGIN_VALIDATOR_VALIDATE-URL: ${APPLICATION_SECURITY_LOGIN_VALIDATOR_VALIDATE_URL}
      # localhost google recaptcha keys
      GOOGLE_RECAPTCHA_ENABLE: ${GOOGLE_RECAPTCHA_ENABLE}
      GOOGLE_RECAPTCHA_KEY_SITE: ${GOOGLE_RECAPTCHA_KEY_SITE}
      GOOGLE_RECAPTCHA_KEY_SECRET: ${GOOGLE_RECAPTCHA_KEY_SECRET}
    networks:
      - ${GLOBAL_NETWORK:-services}